SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for characters
-- ----------------------------
DROP TABLE IF EXISTS `characters`;
CREATE TABLE `characters`  (
  `account_name` varchar(45) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `charId` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `char_name` varchar(35) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `level` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `maxHp` int(10) UNSIGNED NULL DEFAULT NULL,
  `curHp` int(10) UNSIGNED NULL DEFAULT NULL,
  `maxCp` mediumint(8) UNSIGNED NULL DEFAULT NULL,
  `curCp` mediumint(8) UNSIGNED NULL DEFAULT NULL,
  `maxMp` mediumint(8) UNSIGNED NULL DEFAULT NULL,
  `curMp` mediumint(8) UNSIGNED NULL DEFAULT NULL,
  `face` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `hairStyle` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `hairColor` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `sex` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `heading` mediumint(9) NULL DEFAULT NULL,
  `x` mediumint(9) NULL DEFAULT NULL,
  `y` mediumint(9) NULL DEFAULT NULL,
  `z` mediumint(9) NULL DEFAULT NULL,
  `exp` bigint(20) UNSIGNED NULL DEFAULT 0,
  `expBeforeDeath` bigint(20) UNSIGNED NULL DEFAULT 0,
  `sp` bigint(10) UNSIGNED NOT NULL DEFAULT 0,
  `reputation` int(11) NULL DEFAULT NULL,
  `fame` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `raidbossPoints` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `pvpkills` smallint(5) UNSIGNED NULL DEFAULT NULL,
  `pkkills` smallint(5) UNSIGNED NULL DEFAULT NULL,
  `clanid` int(10) UNSIGNED NULL DEFAULT NULL,
  `race` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `classid` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `base_class` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `transform_id` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
  `deletetime` bigint(13) UNSIGNED NOT NULL DEFAULT 0,
  `cancraft` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `title` varchar(21) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `title_color` mediumint(8) UNSIGNED NOT NULL DEFAULT 15530402,
  `accesslevel` mediumint(9) NULL DEFAULT 0,
  `online` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `onlinetime` int(11) NULL DEFAULT NULL,
  `char_slot` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `lastAccess` bigint(13) UNSIGNED NOT NULL DEFAULT 0,
  `clan_privs` int(10) UNSIGNED NULL DEFAULT 0,
  `wantspeace` tinyint(3) UNSIGNED NULL DEFAULT 0,
  `power_grade` tinyint(3) UNSIGNED NULL DEFAULT NULL,
  `nobless` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `subpledge` smallint(6) NOT NULL DEFAULT 0,
  `lvl_joined_academy` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `apprentice` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `sponsor` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `clan_join_expiry_time` bigint(13) UNSIGNED NOT NULL DEFAULT 0,
  `clan_create_expiry_time` bigint(13) UNSIGNED NOT NULL DEFAULT 0,
  `bookmarkslot` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
  `vitality_points` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `createDate` date NOT NULL DEFAULT '2015-01-01',
  `language` varchar(2) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL,
  `faction` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `pccafe_points` int(6) NOT NULL DEFAULT 0,
  `deaths` smallint(6) NOT NULL DEFAULT 0,
  `kills` smallint(6) NOT NULL DEFAULT 0,
  PRIMARY KEY (`charId`) USING BTREE,
  INDEX `account_name`(`account_name`) USING BTREE,
  INDEX `char_name`(`char_name`) USING BTREE,
  INDEX `clanid`(`clanid`) USING BTREE,
  INDEX `online`(`online`) USING BTREE,
  INDEX `idx_char_name`(`char_name`) USING BTREE,
  INDEX `idx_account_name`(`account_name`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
